name: flutter_projects
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  counter_app: ^0.0.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
mockito:
  build_runner:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter




  